export enum ERROR_CODES {
  /**PROGRAMERS ERROR */
  INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR",
  DB_NOT_CONNECTED = "DB NOT CONNECTED",
  METHOD_PARAMS_NOT_VALID = "METHOD PARAMS ARE NOT VALID",

  /**USERS ERROR */
  CREDENTIALS_NOT_VALID = "USER'S CREDENTIALS NOT VALID",
  USER_DOSE_NOT_EXIST = "USER DOSE NOT EXIST",

  USER_USERNAME_EXIST = "USER'S USERNAME ALREADY EXISTS",
  USER_EMAIL_EXIST = "USER'S EMAIL ALREADY EXISTS",

  USER_ID_NOT_VALID = "USER'S ID IS NOT VALID",
  USER_USERNAME_NOT_VALID = "USER'S USERNAME IS NOT VALID",
  USER_EMAIL_NOT_VALID = "USER'S EMAIL IS NOT VALID",
  USER_PASSWORD_NOT_VALID = "USER'S PASSWORD IS NOT VALID",

  USER_NAME_NOT_VALID = "USER'S NAME IS NOT VALID",
  USER_SURNAME_NOT_VALID = "USER'S SURNAME IS NOT VALID",
  USER_NICKNAME_NOT_VALID = "USER'S NICKNAME IS NOT VALID",
  USER_WEIGHT_NOT_VALID = "USER'S WEIGHT IS NOT VALID",
  USER_HIGHT_NOT_VALID = "USER'S HIGHT IS NOT VALID",
};